[package]
name = "reaper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tonic = "0.6"
log = "0.4"
rocket = "0.5.0-rc.1"
prost = "0.9"

[build-dependencies]
tonic-build = { version = "0.6", features = ["rustfmt"] }