apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  serviceName: api
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: api
        image: registry.digitalocean.com/lee-aaron-registry/shuudann-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: APP_REDIS_URI
          value: redis://default:M6SqI6DG3U@my-redis-master.default.svc.cluster.local:6379
        - name: RUST_LOG
          value: error
        - name: APP_DATABASE__USERNAME
          value: admin
        - name: APP_DATABASE__PASSWORD
          value: 3dd6b15890c45f6bb7db
        - name: APP_DATABASE__HOST
          value: my-postgres-postgresql.default.svc.cluster.local
        - name: APP_DATABASE__PORT
          value: '5432'
        - name: APP_DATABASE__DATABASE_NAME
          value: shuudann