apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: kn-letsencrypt-http01-issuer
spec:
  tls:
  - hosts:
    - shuudann.com
    secretName: root-tls
  rules:
  - host: "shuudann.com"
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: api
            port:
              number: 8000
      - pathType: Exact
        path: /webhook
        backend:
          service:
            name: discord
            port:
              number: 9001
      - pathType: Exact
        path: /botcheck
        backend:
          service:
            name: discord
            port:
              number: 9001
      - pathType: Exact
        path: /webhook
        backend:
          service:
            name: discord
            port:
              number: 9001