application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
discord:
  client_id: "966453809335382106"
  client_secret: "A_RnL_ikt2SF6bZ1lyGJhgdKPeQz3hof"
  grant_type: "authorization_code"
  redirect_uri: "http://localhost:3000/api/login"
  frontend_uri: "http://localhost:3000/"
stripe:
  secret_key: "sk_test_7YRSRbVKSQDOG5eFwGhmyNbb008VJ25gVL"