name: Build and Publish Reaper API

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t reaper-api .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag image
        run: docker tag reaper-api registry.digitalocean.com/lee-aaron-reg/reaper-api:latest

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/caffeinated-gorilla/reaper-api:latest

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: reaper-api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}